collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.08960573
  brandStrength: 0.7795699
  lightness: 0.9157706
  brandColors:
    - '#173141'
    - '#415D6F'
    - '#C6CE90'
    - '#BFC543'
    - '#799A42'
  rhythmicContrast: 0.007850284
typography_spectrum: 0.4587814
layout_spectrum: 0.1433692
name: Jeffbrice
