collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4587814
color:
  saturation: 0.4623656
  brandStrength: 0.7795699
  rhythmicContrast: 0.007850284
  brandColors:
    - '#E6D6B6'
    - '#152826'
    - '#A3654B'
    - '#BC9B6D'
  lightness: 0.9157706
layout_spectrum: 0.1433692
name: Jeffbrice
