layout_spectrum: 0.2634408
color:
  saturation: 0.4623656
  lightness: 0.9157706
  brandStrength: 0.7795699
  brandColors:
    - '#E6D6B6'
    - '#152826'
    - '#A3654B'
    - '#BC9B6D'
  rhythmicContrast: 0.007850284
typography_spectrum: 0.4587814
name: Jeffbrice
