typography_spectrum: 0.4587814
color:
  saturation: 0.08960573
  brandStrength: 0.7795699
  rhythmicContrast: 0.007850284
  brandColors:
    - '#173141'
    - '#415D6F'
    - '#C6CE90'
    - '#BFC543'
    - '#799A42'
  lightness: 0.9157706
layout_spectrum: 0.218638
author:
  name: Jeff Brice
  email: jb@jeffbrice.com
name: Jeffbrice
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
